[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "soil_dataprovider_nl"
version = "1.0.0"
authors = [
  { name="Allard de Wit", email="allard.dewit@wur.nl" },
  { name="Herman Berghuijs", email="herman.berghuijs@wur.nl" },
]
maintainers = [
  { name="Allard de Wit", email="allard.dewit@wur.nl" },
  { name="Herman Berghuijs", email="herman.berghuijs@wur.nl" },
]
description = "This package provides a set of data providers that can derive the soil parameters for running crop/soil models in PCSE based on the Dutch soil map."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas",
    "pyproj==3.8",
    "duckdb == 1.5",
]
license = "EUPL-1.2"
license-files = ["LICENSE"]

[project.optional-dependencies]
notebook = ["matplotlib", "ipyleaflet", "pcse>=6.0.13"]

[project.urls]
Homepage = "https://github.com/ajwdewit/soil_dataprovider_nl"
documentation = "https://github.com/ajwdewit/soil_dataprovider_nl"
repository = "https://github.com/ajwdewit/soil_dataprovider_nl"

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true
